name: Aplicação Django

on: [pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.10
          uses: actions/setup-python@v4
          with:
              python-version: '3.10'

        - name: Instalar Depencias
          run: |
              python -m pip install --upgrade pip
              pip install poetry
              poetry install --no-root
        - name: Verificando o estilo do codico com flake8
          run: |
              poetry run flake8
        - name: Rodar testes Automáticos
          run: |
              poetry run pytest --nomigrations